<?php
// No accents here

$bad_words = [
  "nouns" => [
    "gilipollas",
    "cabron",
    "cabrones",
    "diablo",
    "diabla",
    "desgraciado",
    "cabronazo",
    "mierda",
    "joder",
    "cojones",
    "hostia",
    "carajo",
    "pendejo",
    "chingada",
    "culero",
    "puto",
    "verga",
    "cono",
    "capullo",
    "hijoputa",
    "pelotudo",
    "boludo",
    "zorra",
    "maricon",
    "mierdoso",
    "chingon",
    "mamon",
    "huevon",
    "baboso",
    "tarado",
    "imbecil",
    "estupido",
    "mongolico",
    "subnormal",
    "carepicha",
    "soplapollas",
    "chupapollas",
    "pajero",
    "pichacorta",
    "puta",
    "putazo",
    "huevonazo",
    "hijo de puta",
    "hija de puta",
    "hijueputa",
    "malparido",
    "cabestro",
    "mamahuevo",
    "cojudazo",
    "chinga tu madre",
    "picha",
    "pelmazo",
    "chupamedias",
    "tarupido",
    "guevon",
    "forro",
    "pichabrava",
    "papanatas",
    "lechuguino",
    "cagon",
    "sarnoso",
    "apestoso",
    "petardo",
    "tragasables",
    "chupacabras",

    "muerte",
    "suicidio",
    "asesinato",
    "homicidio",
    "violacion",
    "tortura",
    "trafico de personas",
    "genocidio",
    "eutanasia",
    "pena de muerte",
    "terrorismo",
    "guerra",
    "drogas",
    "narcotrafico",
    "sobredosis",
    "adiccion",
    "alcoholismo",
    "prostitucion",
    "pornografia",
    "porno",
    "pedofilia",
    "incesto",
    "canibalismo",
    "enfermedad terminal",
    "cancer",
    "vih",
    "depresion",
    "trastorno mental",
    "esquizofrenia",
    "autolesion",
    "bulimia",
    "anorexia",
    "racismo",
    "xenofobia",
    "homofobia",
    "machismo",
    "misoginia",
    "secta",
    "corrupcion",
    "maltrato",
    "crimen",

    // English
    "dumbass",
    "bastard",
    "shit",
    "fuck",
    "damn",
    "asshole",
    "fuck",
    "asshole",
    "faggot",
    "dick",
    "cunt",
    "jerk",
    "dumbass",
    "moron",
    "slut",
    "faggot",
    "bastard",
    "shitty",
    "badass",
    "jerk",
    "dumbass",
    "fool",
    "idiot",
    "stupid",
    "retard",
    "dumbass",
    "dickhead",
    "cocksucker",
    "wanker",
    "small dick",
    "whore",
    "bitch",
    "big whore",
    "dumbass",
    "son of a bitch",
    "daughter of a bitch",
    "son of a whore",
    "bastard",
    "brute",
    "cocksucker",
    "big idiot",
    "fuck your mother",
    "dick",
    "brown-noser",
    "stupid",
    "dumbass",
    "jerk",
    "horny bastard",
    "idiot",
    "prick",
    "coward",
    "mangy",
    "stinky",
    "firecracker",
    "deepthroat",

    "death",
    "suicide",
    "murder",
    "homicide",
    "rape",
    "torture",
    "human trafficking",
    "genocide",
    "euthanasia",
    "death penalty",
    "terrorism",
    "war",
    "drugs",
    "drug trafficking",
    "overdose",
    "addiction",
    "alcoholism",
    "prostitution",
    "pornography",
    "porn",
    "pedophilia",
    "incest",
    "cannibalism",
    "terminal illness",
    "cancer",
    "hiv",
    "depression",
    "mental disorder",
    "schizophrenia",
    "self-harm",
    "bulimia",
    "anorexia",
    "racism",
    "xenophobia",
    "homophobia",
    "sexism",
    "misogyny",
    "corruption",
    "abuse",
    "crime",

    // French
    "imbecile",
    "connard",
    "connards",
    "gros connard",
    "merde",
    "putain",
    "couilles",
    "hostie",
    "carajo",
    "abruti",
    "pute",
    "encule",
    "bite",
    "con",
    "branleur",
    "fils de pute",
    "pelotudo",
    "idiot",
    "salope",
    "pede",
    "merdeux",
    "baltringue",
    "mouflet",
    "cretin",
    "stupide",
    "mongolique",
    "debile",
    "ducon",
    "suceur",
    "branleur",
    "pichacourt",
    "pute",
    "gros con",
    "fils de pute",
    "fille de pute",
    "encule de mere",
    "batard",
    "mange merde",
    "picha",
    "pelmazo",
    "leche-cul",
    "gueux",
    "glandeur",
    "pauv'con",
    "petard",
    "suceur de sabres",
    "suceur de boules",

    "mort",
    "suicide",
    "assassinat",
    "homicide",
    "viol",
    "torture",
    "traite des etres humains",
    "genocide",
    "euthanasie",
    "peine de mort",
    "terrorisme",
    "guerre",
    "drogues",
    "narcotrafic",
    "overdose",
    "addiction",
    "alcoolisme",
    "prostitution",
    "pornographie",
    "porno",
    "pedophilie",
    "inceste",
    "cannibalisme",
    "maladie terminale",
    "cancer",
    "vih",
    "depression",
    "trouble mental",
    "schizophrenie",
    "automutilation",
    "boulimie",
    "anorexie",
    "racisme",
    "xenophobie",
    "homophobie",
    "machisme",
    "misogynie",
    "secte",
    "corruption",
    "maltraitance",
    "crime",

    "idiot",
    "arschloch",
    "arschlocher",
    "riesenarschloch",
    "scheisse",
    "verdammt",
    "eier",
    "hostie",
    "carajo",
    "depp",
    "hure",
    "wichser",
    "schwanz",
    "trottel",
    "wichser",
    "hurensohn",
    "pelotudo",
    "idiot",
    "schlampe",
    "schwuchtel",
    "scheisskerl",
    "feigling",
    "verlierer",
    "trottel",
    "dummkopf",
    "bloede",
    "mongo",
    "debil",
    "du dummer",
    "lutscher",
    "wichser",
    "kurzer schwanz",
    "hure",
    "riesentrottel",
    "hurensohn",
    "bastard",
    "scheisskerl",
    "pimmel",
    "versager",
    "scheisskopf",
    "opfer",
    "mistkerl",

    "tod",
    "selbstmord",
    "mord",
    "toetung",
    "vergewaltigung",
    "folter",
    "menschenhandel",
    "voelkermord",
    "euthanasie",
    "todesstrafe",
    "terrorismus",
    "krieg",
    "drogen",
    "drogenhandel",
    "ueberdosis",
    "sucht",
    "alkoholismus",
    "prostitution",
    "pornografie",
    "porno",
    "paedophilie",
    "inzest",
    "kannibalismus",
    "todskrankheit",
    "krebs",
    "hiv",
    "depression",
    "geisteskrankheit",
    "schizophrenie",
    "selbstverletzung",
    "bulimie",
    "anorexie",
    "rassismus",
    "fremdenfeindlichkeit",
    "homophobie",
    "sexismus",
    "misogynie",
    "sekte",
    "korruption",
    "misshandlung",
    "verbrechen",

    "idiota",
    "stronzo",
    "stronzi",
    "grandissimo stronzo",
    "merda",
    "cazzo",
    "palle",
    "ostia",
    "carajo",
    "deficiente",
    "puttana",
    "segaiolo",
    "cazzo",
    "cretino",
    "bastardo",
    "pelotudo",
    "idiota",
    "troia",
    "frocio",
    "merdoso",
    "figlio di puttana",
    "coglione",
    "fallito",
    "ritardato",
    "imbecille",
    "stupido",
    "mongoloide",
    "subnormale",
    "succhiacazzi",
    "masturbatore",
    "cazzone",
    "grandissima puttana",
    "figlio di puttana",
    "figlia di puttana",
    "bastardo",
    "mangiamerda",
    "pisello",
    "scemo",
    "leccaculo",
    "fesso",
    "pallemosce",
    "pappamolla",
    "cagasotto",
    "puzzolente",
    "testa di cazzo",
    "succa spade",

    "morte",
    "suicidio",
    "omicidio",
    "assassinio",
    "uccisione",
    "stupro",
    "tortura",
    "tratta di esseri umani",
    "genocidio",
    "eutanasia",
    "pena di morte",
    "terrorismo",
    "guerra",
    "droga",
    "narcotraffico",
    "overdose",
    "dipendenza",
    "alcolismo",
    "prostituzione",
    "pornografia",
    "porno",
    "pedofilia",
    "incesto",
    "cannibalismo",
    "malattia terminale",
    "cancro",
    "hiv",
    "depressione",
    "disturbo mentale",
    "schizofrenia",
    "autolesionismo",
    "bulimia",
    "anoressia",
    "razzismo",
    "xenofobia",
    "omofobia",
    "maschilismo",
    "misoginia",
    "setta",
    "corruzione",
    "maltrattamento",
    "crimine",
  ],

  "verbs" => [
    "insultar",
    "agredir",
    "follar",
    "acosar",
    "estafar",
    "engañar",
    "robar",
    "matar",
    "asesinar",
    "envenenar",
    "apuñalar",
    "secuestrar",
    "violar",
    "abusar",
    "chantajear",
    "extorsionar",
    "torturar",
    "oprimir",
    "traficar",
    "prostituir",
    "drogar",
    "emborrachar",
    "cagar",
    "masturbar",
    "fornicar",
  ]
];